<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPMBWx8d\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPMBWx8d/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPMBWx8d.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPMBWx8d\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPMBWx8d\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PMBWx8d',
    'container.build_id' => 'c0a936fc',
    'container.build_time' => 1572383422,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPMBWx8d');
